### ISSUE TITLE
api接口查询500报错

### ISSUE THREAD

**Issue by 7estUser** [wuba/Antenna#101]
docker环境api接口查询500报错，查看日志没有详细报错内容
![image](https://user-images.githubusercontent.com/85153024/229468410-4ed47676-529f-4bc9-9310-005f76a1b994.png)

**Comment by bios000** [comment]
请给出您的请求URL

**Comment by bios000** [comment]
已在最新版本代码中修复，请重新下载最新镜像使用，感谢
