### ISSUE TITLE
任务管理新建报错500

### ISSUE THREAD

**Issue by 7estUser** [wuba/Antenna#102]
任务管理-新建-500报错
![image](https://user-images.githubusercontent.com/85153024/229472268-b3878744-3341-4f4d-86b9-26d5011beba7.png)

**Comment by 7estUser** [comment]
docker环境下

**Comment by bios000** [comment]
将在本周新版本修复

**Comment by bios000** [comment]
已在v1.3.4-fix版本修复，请重新下载最新版本镜像使用，感谢
