### ISSUE TITLE
博客访问异常

### ISSUE THREAD

**Issue by Explorer1092** [wuba/Antenna#131]
root@MacBook-Pro-M2 ~ % dig blog.antenna.cool @8.8.8.8

; <<>> DiG 9.10.6 <<>> blog.antenna.cool @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36027
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;blog.antenna.cool.		IN	A

;; ANSWER SECTION:
blog.antenna.cool.	600	IN	A	8.219.104.156

;; Query time: 600 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Jul 29 17:39:59 CST 2023
;; MSG SIZE  rcvd: 62

user@MacBook-Pro-M2 ~ %

**Comment by bios000** [comment]
已恢复
