### ISSUE TITLE
域名解析失败

### ISSUE THREAD

**Issue by mingones** [wuba/Antenna#135]
1111

**Comment by dashuai785** [comment]
hi，开发者您好，我尝试使用docker部署Antenna，所有步骤以及域名解析都以官网为准，但是最终结果是域名无法收到有效解析（等待时间超好12小时） 有一下差异点： 1、在“阿里云域名配置DNS”中“点击同步后回到Antenna系统保存协议相关设置” 中系统没有对应的协议设置 2、docker logs出现“(1146, "Table 'antenna.config' doesn't exist")” 有空的时候麻烦您帮忙看下~
