### ISSUE TITLE
[需求] Dns ReBinding

### ISSUE THREAD

**Issue by XTeam-Wing** [wuba/Antenna#15]
增加DNS重绑定

**Comment by bios000** [comment]
已经加在需求列表里了，会有的

**Comment by bios000** [comment]
> 增加DNS重绑定

DNS报错是由于pycharm插件自动缩进导致解析表解析错误导致的，已修改

**Comment by bios000** [comment]
> 增加DNS重绑定

重绑定预计本周末上线

**Comment by bios000** [comment]
今晚v1.3.0版本上线，已支持DNS_REBINDING设置
