### ISSUE TITLE
提交一个需求：支持https，记录完整请求头

### ISSUE THREAD

**Issue by coffeehb** [wuba/Antenna#2]
1、支持https服务，方便兼容一些业务场景
2、记录完整请求头，方便测试发现外带请求头中泄露的非常规字段的敏感信息。比如：
Token：xxxx

**Comment by bios000** [comment]
你是说https请求监听吗，能具体说一下使用场景吗

**Comment by coffeehb** [comment]
> 你是说https请求监听吗，能具体说一下使用场景吗

对的。HTTPS利用组件 监听组件。比如，APP里Webview打开的网页中，随意点击里面的URL会在请求头里面插入了用户的登录凭证，这个时候需要有这样的可以监听https的地址，方便测试。https中打开http链接，会报错。

**Comment by bios000** [comment]
后端已实现，关于系统的前端展示得工作日去和前端沟通，预计下周上线

**Comment by bios000** [comment]
> > 你是说https请求监听吗，能具体说一下使用场景吗
> 
> 对的。HTTPS利用组件 监听组件。比如，APP里Webview打开的网页中，随意点击里面的URL会在请求头里面插入了用户的登录凭证，这个时候需要有这样的可以监听https的地址，方便测试。https中打开http链接，会报错。

当前已经支持全header头记录，https等其余协议支持将在近期一齐增加

**Comment by bios000** [comment]
所有需求已支持
