### ISSUE TITLE
无法接收POST请求，GET请求无法接收参数

### ISSUE THREAD

**Issue by coffeehb** [wuba/Antenna#30]
随意监听一个HTTP组件
复现：

http://xxx.xxx.fun/whoami?=1122222

curl -A o -o- -L -F file=@/etc/hosts http://xxx.xxx.fun/

查看记录，GET无参数记录，只有URI
POST直接返回报错。

{"code":0,"message":"Method \"POST\" not allowed.","data":{}}

**Comment by bios000** [comment]
当前版本可使用message参数添加自定义内容，关于post请求将在下个版本支持
