### ISSUE TITLE
能否新增定时清理功能

### ISSUE THREAD

**Issue by shadow1ng** [wuba/Antenna#55]
新增设置，可自定义几天清理一次数据。
因为很多时候数据都是ssrf或测试数据，不需要长期保留，所以有定时清理的话，会清晰一些

**Comment by shadow1ng** [comment]
然后源码搭建时。如果配置了mysql账号密码，就去连接。否则可以使用sqlite数据库，这样比较轻便。

**Comment by bios000** [comment]
今晚发布v1.3.0版本，新增只保留七天内信息配置
