### ISSUE TITLE
docker启动，53端口权限问题

### ISSUE THREAD

**Issue by xiaolushuo** [wuba/Antenna#8]
### 环境
 * 阿里云
 * CentOS Linux release 7.7.1908 (Core)
### 问题
 启动报错，如下

![WechatIMG3](https://user-images.githubusercontent.com/16830990/187175359-e118e8a9-c448-4236-8020-e4bc72131e00.png)

这是因为docker内运行脚本的用户权限问题导致的，删除Dockerfile文件的以下三行，删除旧镜像，重新构建即可。
![Snipaste_2022-08-29_17-56-26](https://user-images.githubusercontent.com/16830990/187175861-cd65b3c1-c513-4c3e-9ed5-1e0cc609ec4f.png)

**Comment by bios000** [comment]
这个为docker 安全权限组设置，如果遇到该问题可按照此方案解决，没有的话可不用修改，感谢提交
